# Generated by Django 5.0.4 on 2024-04-18 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('optimization_status', models.CharField(default='Not started', max_length=200)),
                ('last_optimization_result', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_file', models.FileField(upload_to='optimized_files/')),
                ('optimization_result', models.TextField(blank=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_files', to='optimizer.file')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('optimized_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.optimizedfile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('optimized_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.optimizedfile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('optimized_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.optimizedfile')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.website'),
        ),
    ]
