# Generated by Django 5.0.4 on 2024-04-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/0'),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
