# Generated by Django 5.0.4 on 2024-04-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_alter_file_file_alter_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_chosen', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('optimization_result', models.CharField(max_length=100)),
            ],
        ),
    ]
