# Generated by Django 5.0.4 on 2024-04-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_viewwebsite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewWebsite',
        ),
    ]
