# Generated by Django 5.0.4 on 2024-05-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0005_delete_viewwebsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='url',
        ),
        migrations.AddField(
            model_name='website',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zip_files/'),
        ),
    ]
